/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesLogin;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tadeo
 */
public class registro extends javax.swing.JPanel {

    Color foregroundColor = Color.black;

    /**
     * Creates new form Registro
     */
    public registro() {
        initComponents();
    }
    
    private void mostrarPaneles(JPanel panel) {
        panel.setSize(818, 410);
        panel.setLocation(0, 0);

        Registro.removeAll();
        Registro.add(panel, BorderLayout.CENTER);
        Registro.revalidate();
        Registro.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pswSecreto = new javax.swing.JPasswordField();
        pswContra = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(342, 420));

        Registro.setBackground(new java.awt.Color(197, 223, 248));
        Registro.setForeground(new java.awt.Color(0, 0, 0));
        Registro.setMinimumSize(new java.awt.Dimension(342, 376));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOMBRES:");

        txtNombres.setBackground(new java.awt.Color(197, 223, 248));
        txtNombres.setForeground(new java.awt.Color(51, 51, 51));
        txtNombres.setText("Ingrese sus nombres:");
        txtNombres.setBorder(null);
        txtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombresMousePressed(evt);
            }
        });
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("APELLIDOS: ");

        txtApellidos.setBackground(new java.awt.Color(197, 223, 248));
        txtApellidos.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidos.setText("Ingrese sus apellidos:");
        txtApellidos.setBorder(null);
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosMousePressed(evt);
            }
        });
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CONTRASEÑA: ");

        btnRegistro.setText("REGISTRARME");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("VERIFIQUE LA CONTRASEÑA ");

        pswSecreto.setBackground(new java.awt.Color(197, 223, 248));
        pswSecreto.setForeground(new java.awt.Color(51, 51, 51));
        pswSecreto.setText("**********");
        pswSecreto.setBorder(null);
        pswSecreto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswSecretoMousePressed(evt);
            }
        });

        pswContra.setBackground(new java.awt.Color(197, 223, 248));
        pswContra.setForeground(new java.awt.Color(51, 51, 51));
        pswContra.setText("**********");
        pswContra.setBorder(null);
        pswContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswContraMousePressed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CORREO");

        txtCorreo.setBackground(new java.awt.Color(197, 223, 248));
        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setText("Ingrese su correo:");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro);
        Registro.setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistroLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3))))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel10))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistroLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnRegistro))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator5)
                                .addComponent(pswSecreto, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                .addGap(82, 82, 82))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGap(4, 4, 4)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswSecreto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistro))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresMousePressed
        // TODO add your handling code here:
        if (txtNombres.getText().equals("Ingrese sus nombres:")) {
            txtNombres.setText("");
        }
//        if (txtApellidos.getText().isEmpty() || String.valueOf(pswContra.getPassword()).isEmpty() || String.valueOf(pswSecreto.getPassword()).isEmpty()) {
//            txtApellidos.setText("Ingrese sus apellidos:");
//            txtApellidos.setForeground(Color.black);
//            pswContra.setText("**********");
//            pswSecreto.setText("**********");
//        }
//        if (txtDia.getText().isEmpty() || txtMes.getText().isEmpty() || txtAnio.getText().isEmpty()) {
//            txtDia.setText("DIA");
//            
//            txtMes.setText("MES");
//            
//            txtAnio.setText("Año");
//        }
        // Color foregroundColor = Color.black; // Assuming you want black for all

        if (txtApellidos.getText().isEmpty()) {
            txtApellidos.setText("Ingrese sus apellidos:");
            txtApellidos.setForeground(foregroundColor);
        }

        if (String.valueOf(pswContra.getPassword()).isEmpty()) {
            pswContra.setText("**********");
            pswContra.setForeground(foregroundColor);
        }

        if (String.valueOf(pswSecreto.getPassword()).isEmpty()) {
            pswSecreto.setText("**********");
            pswSecreto.setForeground(foregroundColor);
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo:");
        }

    }//GEN-LAST:event_txtNombresMousePressed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMousePressed
        // TODO add your handling code here:
        if (txtApellidos.getText().equals("Ingrese sus apellidos:")) {
            txtApellidos.setText("");
        }
        //Emptys o correcciones por si no hay texto en casillas 
        if (txtNombres.getText().isEmpty()) {
            txtNombres.setText("Ingrese sus nombres:");
        }

        if (String.valueOf(pswContra.getPassword()).isEmpty()) {
            pswContra.setText("**********");
            pswContra.setForeground(foregroundColor);
        }

        if (String.valueOf(pswSecreto.getPassword()).isEmpty()) {
            pswSecreto.setText("**********");
            pswSecreto.setForeground(foregroundColor);
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo:");
        }

    }//GEN-LAST:event_txtApellidosMousePressed

    private void pswContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContraMousePressed
        // TODO add your handling code here:
        if (String.valueOf(pswContra.getPassword()).equals("**********")) {
            pswContra.setText("");
        }
        //Emptys para casillas vacias
        if (txtNombres.getText().isEmpty()) {
            txtNombres.setText("Ingrese sus nombres:");
        }

        if (txtApellidos.getText().isEmpty()) {
            txtApellidos.setText("Ingrese sus apellidos:");
            txtApellidos.setForeground(foregroundColor);
        }

        if (String.valueOf(pswSecreto.getPassword()).isEmpty()) {
            pswSecreto.setText("**********");
            pswSecreto.setForeground(foregroundColor);
        }

        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo:");
        }

    }//GEN-LAST:event_pswContraMousePressed

    private void pswSecretoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswSecretoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(pswSecreto.getPassword()).equals("**********")) {
            pswSecreto.setText("");
        }
        //Emptys para casillas vacias
        if (txtNombres.getText().isEmpty()) {
            txtNombres.setText("Ingrese sus nombres:");
        }

        if (txtApellidos.getText().isEmpty()) {
            txtApellidos.setText("Ingrese sus apellidos:");
            txtApellidos.setForeground(foregroundColor);
        }

        if (String.valueOf(pswContra.getPassword()).isEmpty()) {
            pswContra.setText("**********");
            pswContra.setForeground(foregroundColor);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo:");
        }


    }//GEN-LAST:event_pswSecretoMousePressed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        
        /*Pasos que se realizaran para insertan los datos de un usuario a la base de datos 
        1-Recibir los datos del JTextField y JPasswordField 
        2-Compara y busca el correo en la base de datos
        3-Se atrae el correo, y se compara el de la base de datos con el del JTextField
        4-Si el correo ya esta entonces pide uno diferente
        5-Si el correo no esta entonces procede 
        6-Con lo datos ingresados se realizara un INSERT INTO 
        7-Cuando se realice el INSEERT INTO entonces cambiara el panel al del login para iniciar sesion 
        */
        
        try{
            ResultSet rs= null;
            PreparedStatement ps = null;
            String nombres =txtNombres.getText();
            String apellidos =txtApellidos.getText();
            String correo = txtCorreo.getText();
            String contra=String.valueOf(pswContra.getPassword());
            String secreto=String.valueOf(pswSecreto.getPassword());
            String noCuenta=" ";
            String clave = " ";
            String saldo = "";
            
            ConexionBd.Conexion objetoConexion = new ConexionBd.Conexion();
            String comparaCond = "SELECT correo FROM banco.cuentasusuarios WHERE correo=? ;";
            ps=objetoConexion.establecerConexion().prepareStatement(comparaCond);
            
            ps.setString(1,correo);
            
            rs=ps.executeQuery();
            if(rs.next()){
                //Se obtiene el correo que esta en base de datos 
                String email=rs.getString("correo");
               
                //Si el correo de la base de datos existe y es igual entonces se muestra el siguiente panel 
                if(correo.equals(email)){
                    
                JOptionPane.showMessageDialog(null, "Correo existente. Ingrese uno diferente");
            }
            }else{
                JOptionPane.showMessageDialog(null, "Correo no encontrado");
                //Si no hay ningun correo entonces procede con el INSERT INTO 
 String agregar ="INSERT INTO banco.cuentasusuarios(nombres,apellidos,correo,contraseña,noCuenta,clave,saldo) VALUES (?,?,?,?,?,?,?);"  ;
            ps=objetoConexion.establecerConexion().prepareStatement(agregar);
            ps.setString(1, nombres);
            ps.setString(2, apellidos);
            ps.setString(3, correo);
            ps.setString(4,contra);
            ps.setString(5, noCuenta);
            ps.setString(6,clave);
            ps.setString(7, saldo);
            
            int datosAgregados=ps.executeUpdate();
            if(datosAgregados>0){
                JOptionPane.showMessageDialog(null,"Hola "+nombres+" Bienvenido ");
                Inicio.Login llamar = new Inicio.Login();
                llamar.dispose();
                
            }

            }

        }catch(Exception e ){
            
        }
        
        
        
        //El siguiente codigo son las que limitaran ciertas acciones como el ingresar datos cuando 
        if (String.valueOf(pswContra.getPassword()).equals("**********") || String.valueOf(pswSecreto.getPassword()).equals("**********")) {
            JOptionPane.showMessageDialog(null, "Escriba una contraseña correcta");
        }

        String[] cajasTexto = {txtNombres.getText(), txtApellidos.getText()};
        String[] defecto = {"Ingrese sus nombres:", "Ingrese sus apellidos:"};
        int noAcept = 0;
        int cont = 0;
        for (cont = 0; cont < cajasTexto.length; cont++) {
            if (cajasTexto[cont].isEmpty() || cajasTexto[cont].equals(defecto[cont])) {
                noAcept = noAcept + 1;

            }
        }
        if (noAcept > 0) {
            JOptionPane.showMessageDialog(null, "Ingrese datos correctos en " + noAcept + " casillas ");
        }


    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if(txtCorreo.getText().equals("Ingrese su correo:")){
            txtCorreo.setText("");
            txtCorreo.setForeground(foregroundColor);
        }
        
         if (txtNombres.getText().isEmpty()) {
            txtNombres.setText("Ingrese sus nombres:");
        }

        if (txtApellidos.getText().isEmpty()) {
            txtApellidos.setText("Ingrese sus apellidos:");
            txtApellidos.setForeground(foregroundColor);
        }

        if (String.valueOf(pswContra.getPassword()).isEmpty()) {
            pswContra.setText("**********");
            pswContra.setForeground(foregroundColor);
        }
        
    }//GEN-LAST:event_txtCorreoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Registro;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JPasswordField pswSecreto;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
